### PR TITLE
Reports check

### PR DESCRIPTION
**Pull request by kisiro55**
Some few changes on the methods: 
-  Moved  "invoiced_paid_array = []" inside do loop
- Corrected an error i had on the for loop (fy_start eliminated and changed for fy_end)

No changes on the visual side.
image

### CODE REVIEW

**Comment by kisiro55** [comment]
@lux9 could you please provide some help in refactoring this code? its functional but is larger than desired. 

line 177- 200 on reports_controller.rb

image

**Comment by kisiro55** [comment]
@hankhng 

I've changed the id styles for a class to have grey fonts on tabs corresponding to the reports section.  Please have a look and check if you like it. I personally prefer it vs the blue we have before as default without hovering.


image

**Comment by kisiro55** [comment]
Added style to Taxes tab.

image

**Comment by hank-hng** [comment]
> @hankhng
> 
> I've changed the id styles for a class to have grey fonts on tabs corresponding to the reports section. Please have a look and check if you like it. I personally prefer it vs the blue we have before as default without hovering.
> 
> image

Yeah sure no probs!

**Pull request merged**
