### PR TITLE
vertical navbar

### PR DESCRIPTION
**Pull request by thomasvanholder**
Screenshot 2020-04-07 at 17 14 24

### CODE REVIEW

**Comment by thomasvanholder** [comment]
the grey space is the standard background for the page
it's a smaller cut screenshot

**Comment by lux9** [comment]
Hi @thomasvanholder! It looks great! But are you gonna use it on the home too? Or u re not gonna use home route yet?


`.navbar-lewagon {
	justify-content: space-between;
	background: white;
	margin-left: 213px;
}`
That **margin-left** is gonna change the navbar wherever you render it, even if you don't have a sidebar.

Screen Shot 2020-04-07 at 17 44 11

**Comment by thomasvanholder** [comment]
Good catch. On the home page, there will be no vertical navbar.

**Comment by kkittlive** [comment]
Thomas has confirmed the code in the pages/sidebar.html.erb is temporary for testing - so we will merge this PR and down the road the code in there will be removed

**Pull request merged**
