### PR TITLE
Calendar (v1 ready for review)

### PR DESCRIPTION
**Pull request by hankhng**
WIP for @lux9 to review

### CODE REVIEW

**Comment by hankhng** [comment]
Added new style with Feli with yarn add plugins

image

**Comment by hank-hng** [comment]
Adding event works:

image
image
image

Ready for this to be committed and begin next part of the feature which is pop up modal and requesting information via simple form and persisting to database.

**Comment by hankhng** [comment]
@Elmolesto 
This line needs checking as I'm getting an extra day with my query selector. If I do -1 then on first days of the month, where it is 1, then it will be 0. 

image

**Comment by hankhng** [comment]
Pop up modal for new shifts working

image

**Comment by hankhng** [comment]
Ran migration @Elmolesto

**Pull request merged**
